spring:
  datasource:
    url: jdbc:mysql://139.9.168.137:3306/cmp_n?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: xzl12345+
    hikari:
      maximum-pool-size: 1
      idle-timeout: 10000
      keepalive-time: 0
#mybatis:
#  mapper-locations:  com.cqx.springboot.mapper