spring:
    application:
        name: learning-spring
    banner:
      location: classpath:banner-girl.txt
server:
  port: 80
logging:
   file: /logs/stn.log
   level:
     root: debug

# 设置spring boot 启动的banner
feign:
  okhttp:
    enabled: true
  hystrix:
    enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3000
debug: true
